
FROM python:3.10.6-slim

WORKDIR /app

# Install dependensi sistem untuk OpenCV dan pemrosesan gambar
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

# Salin requirements file dan install dependensi Python
COPY requirements.txt .
RUN pip install --no-cache-dir --default-timeout=1000 --retries 5 -r requirements.txt

COPY . .

# Expose port Flask
EXPOSE 7860

# Jalankan aplikasi 
CMD ["python", "app.py"]